### ISSUE TITLE
Second sign attempt causing User gesture is not detected warning

### ISSUE THREAD

**Issue by SimonVillage** [tkhq/demo-passkey-wallet#3] opened 2023-11-23 03:41 UTC
On iOS, Safari, if a user cancels the passkey requests and tries again, a warning is thrown `User gesture is not detected. To use the WebAuthn API, call 'navigator.credentials.create' or 'navigator.credentials.get' within user activated events.` and the user can't sign again until he reloads the website.

To reproduce this, the button has to be re-enabled as the signing request sets the disabled property to the button.

### Steps to reproduce

1. on iOS Safari open https://wallet.tx.xyz sign in / up and claim some Sepolia ETH
2. try to make a withdrawal but cancel the passkey request
3. remove the button disabled state and try again
4. A console warning is thrown `User gesture is not detected.` and the request fails

I would say that about 30% of our beta users had issues with this and were forced to restart the app to make signing work again.

I posted this in the demo repo as it's easy to reproduce here.

**Comment by SimonVillage** [comment] 2023-11-26 00:48
@andrewkmin @r-n-o are you aware of this issue and able to reproduce it? I am trying to figure out if we stay with turnkey or implement another solution as we have a high drop-off rate with this issue.

**Comment by andrewkmin** [comment] 2023-11-26 03:13
Hey @SimonVillage, sorry for the delayed response. On my iOS device, I can indeed repro the issue of the button remaining disabled after canceling the native passkey modal. However, in terms of this demo, it seems to be something that can be resolved by slightly tweaking our management of the button state (a simple refresh gets the page into a state in which the passkey request can succeed).

Would love to help you get to the bottom of this, but we may need more context on how your app is being run. PWA? Where/how is the console warning being thrown? Feel free to reach out to help@turnkey.com as well

**Comment by SimonVillage** [comment] 2023-11-26 03:40
Thanks for getting back. The issue isn't really related to the button state but recalling the passkey / signing function. Try fixing the button state and then cancel the first passkey request. After that a repeated call to passkey is not possible.

**Comment by r-n-o** [comment] 2023-11-26 15:28
I know it won't directly solve your issue but here's a PR to handle errors better so we can reproduce on wallet.tx.xyz without fiddling with enabled/disabled states: https://github.com/tkhq/demo-passkey-wallet/pull/4

**Comment by r-n-o** [comment] 2023-11-26 15:41
Looking online a bit I found this article: https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS -- I think the lack of error handling might be to blame here, and the second tap isn't considered a real user gesture for some reason.

When my branch gets merged/deployed I'm hoping iOS will classify the second tap as a real "user gesture" and the problem might go away? I'm cautiously optimistic.

**Comment by SimonVillage** [comment] 2023-11-27 07:50
Thanks for the PR #4 

The problem still exists, passkey isn't requested a second time, however, now the error `This request has been cancelled by the user.` shows once you try again. I am not sure if this is a general problem of iOS as it's possible to repeatedly call the passkey function on the webauthn demo as example. https://webauthn.io

**Comment by r-n-o** [comment] 2023-11-27 14:54
@SimonVillage yep! I can reliably repro on my end now. I don't think it's something fundamental to webauthn. Looks like some sort of caching behavior maybe? Wondering if it has something to do with the way we've set up forms/state in the demo wallet. We'll circle back once we have a potential explanation or fix, thanks for bringing this to our attention!

**Comment by r-n-o** [comment] 2023-11-28 18:09
@SimonVillage good news, I figured out why this is happening: it's because we have an extra async call before the passkey call in our stamper. More specifically, here: https://github.com/tkhq/sdk/blob/bed2beaa87fd4b1024207bb450e0847c744a4d2c/packages/webauthn-stamper/src/index.ts#L72

Locally I've replaced the native browser sha256 (which is asynchronous, go figure!) with a synchronous version (from `@noble/hashes`) and it resolved the issue!

I'll circle back here once we've updated this repo with a fixed version of `@turnkey/webauthn-stamper`.

**Comment by SimonVillage** [comment] 2023-11-29 02:53
Seems like this was already merged and released on npm? https://wallet.tx.xyz isn't updated yet I assume?

I tried again on my localhost and can still reproduce the issue. Was it working for you? Is everything already released?

**Comment by r-n-o** [comment] 2023-11-29 03:24
@SimonVillage it's been released on npm but I hadn't bumped the packages in this repo yet. Done now: https://github.com/tkhq/demo-passkey-wallet/pull/7 (merged and deployed).

Logging into https://wallet.tx.xyz on my ios device I'm able to cancel the first passkey prompt when trying to send some ETH and get a successful subsequent prompt.

Let me know if you're still running into issues!

**Comment by SimonVillage** [comment] 2023-11-29 07:34
Seems like the demo is working now, thanks.

Do you have any idea why it's still failing here: https://github.com/tkhq/demo-viem-passkeys/blob/d38929372ded018250669d611cff9c48e4968ab7/src/pages/index.tsx#L75-L102

The `Create ETH address` function contains only 1 async call to the `passkeyHttpClient.stampCreatePrivateKeys` function. It's failing the second attempt with the same reason we discussed here.

**Comment by r-n-o** [comment] 2023-11-29 15:50
@SimonVillage that makes sense, the code you linked is part of a separate repo, and the fix hasn't been applied there yet: I see an old version of webauthn-stamper:
https://github.com/tkhq/demo-viem-passkeys/blob/d38929372ded018250669d611cff9c48e4968ab7/package.json#L18

So even though it looks like there is only one async call, there's actually 2 because old version of webauthn-stamper use the async crypto.subtle.digest method to compute the payload sha.

Let's followup in that repo, I've opened an PR to bump packages and update the demo more generally: https://github.com/tkhq/demo-viem-passkeys/pull/1

I'll close this issue given the code in the demo-passkey-wallet repo is now working as expected (thanks for confirming!)

**Closed as completed by r-n-o** 2023-11-29 15:50 UTC
